name: Setup CI (Scripts)
on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}

      # needed for response time
      - name: give permissions to installation script  
        run: chmod +x ./scripts/installation.sh
      - name: Run installation script
        run: ./scripts/installation.sh

      - name: Update template
        uses: jayantkatia/uptime-monitor@scripts-enabled
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Update response time
        uses: jayantkatia/uptime-monitor@scripts-enabled
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          MY_WS_U: ${{ secrets.MY_WS_U }}
          MY_WS_P: ${{ secrets.MY_WS_P }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Update summary in README
        uses: jayantkatia/uptime-monitor@scripts-enabled
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Graphs CI
          token: ${{ secrets.GH_PAT }}

      - name: Generate site
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - uses: peaceiris/actions-gh-pages@v3.7.3
        name: GitHub Pages Deploy
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: "site/status-page/__sapper__/export/"
          user_name: "Upptime Bot"
          user_email: "73812536+upptime-bot@users.noreply.github.com"
