name: Summary CI (Scripts)
on:
  schedule:
    - cron: "0 0 1 1 *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Update summary in README
        uses: jayantkatia/uptime-monitor@scripts-enabled
        with:
          command: readme
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GH_PAT }}
          query: "topic:upptime"
          size: 20
          max: 1000
          one-per-owner: true
