name: Uptime CI (Scripts)
on:
  schedule:
    - cron: "0 0 1 1 *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}

      - name: give permissions to installation script  
        run: chmod +x ./scripts/installation.sh

      - name: Run installation script
        run: ./scripts/installation.sh

      - name: Check endpoint status
        uses: jayantkatia/uptime-monitor@scripts-enabled
        with:
          command: update
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          MY_WS_U: ${{ secrets.MY_WS_U }}
          MY_WS_P: ${{ secrets.MY_WS_P }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
